<a href="https://colab.research.google.com/github/26Kenn07/Pytorch/blob/main/Day2_Tensors_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Lists

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
my_list2 = [[1,2,3,4], [3,4,5]]
my_list2

[[1, 2, 3, 4], [3, 4, 5]]

# Numpy

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.80740178, 0.16482761, 0.00605878, 0.89687468],
       [0.10483313, 0.76069012, 0.53877098, 0.63902431],
       [0.18886502, 0.45086697, 0.17669101, 0.50853728]])

In [6]:
np1.dtype

dtype('float64')

# Tensor

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.2075,  0.0153,  1.6351, -0.9831],
        [ 0.1101,  0.2035,  1.9766, -2.1839],
        [-0.2940,  0.9079,  0.8214,  0.8025]])

In [10]:
tensor_2d.dtype

torch.float32

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
#Create tensor from numpy array
tensor = torch.tensor(np1)
tensor

tensor([[0.8074, 0.1648, 0.0061, 0.8969],
        [0.1048, 0.7607, 0.5388, 0.6390],
        [0.1889, 0.4509, 0.1767, 0.5085]], dtype=torch.float64)