<a href="https://colab.research.google.com/github/26Kenn07/Pytorch/blob/main/Day_4_Tensor_Maths_Operations_Pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([2,3,4,5])

# Addition

In [3]:
tensor_a + tensor_b

tensor([3, 5, 7, 9])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([3, 5, 7, 9])

In [16]:
tensor_a.add(tensor_b)

tensor([3, 5, 7, 9])

# Sutraction

In [5]:
tensor_b - tensor_a

tensor([1, 1, 1, 1])

In [6]:
torch.sub(tensor_b, tensor_a)

tensor([1, 1, 1, 1])

# Multplication

In [7]:
tensor_a * tensor_b

tensor([ 2,  6, 12, 20])

In [8]:
torch.mul(tensor_a, tensor_b)

tensor([ 2,  6, 12, 20])

# Division

In [9]:
tensor_b / tensor_a

tensor([2.0000, 1.5000, 1.3333, 1.2500])

In [10]:
torch.div(tensor_b, tensor_a)

tensor([2.0000, 1.5000, 1.3333, 1.2500])

In [11]:
tensor_b % tensor_a

tensor([0, 1, 1, 1])

In [14]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [15]:
torch.pow(tensor_a, tensor_b)

tensor([   1,    8,   81, 1024])

In [17]:
#Reassignment_
tensor_a = tensor_a + tensor_b
tensor_a

tensor([3, 5, 7, 9])

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_a.add_(tensor_b)
tensor_a

tensor([3, 5, 7, 9])